# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
os: osx

language: node_js

node_js:
  - '12'

notifications:
  email: false

cache:
  yarn: true

script:
  - yarn lint
  - yarn dist
  - yarn test
